/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = LaunchDarklyAPI.Client.SwaggerDateConverter;

namespace LaunchDarklyAPI.Model
{
    /// <summary>
    /// Statement
    /// </summary>
    [DataContract]
    public partial class Statement :  IEquatable<Statement>, IValidatableObject
    {
        /// <summary>
        /// Defines Effect
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EffectEnum
        {
            
            /// <summary>
            /// Enum Allow for value: allow
            /// </summary>
            [EnumMember(Value = "allow")]
            Allow = 1,
            
            /// <summary>
            /// Enum Deny for value: deny
            /// </summary>
            [EnumMember(Value = "deny")]
            Deny = 2
        }

        /// <summary>
        /// Gets or Sets Effect
        /// </summary>
        [DataMember(Name="effect", EmitDefaultValue=false)]
        public EffectEnum? Effect { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Statement" /> class.
        /// </summary>
        /// <param name="resources">resources.</param>
        /// <param name="notresources">Targeted resource will be those resources NOT in this list. The \&quot;resources&#x60;\&quot; field must be empty to use this field..</param>
        /// <param name="actions">actions.</param>
        /// <param name="notactions">Targeted actions will be those actions NOT in this list. The \&quot;actions\&quot; field must be empty to use this field..</param>
        /// <param name="effect">effect.</param>
        public Statement(Resources resources = default(Resources), Resources notresources = default(Resources), Actions actions = default(Actions), Actions notactions = default(Actions), EffectEnum? effect = default(EffectEnum?))
        {
            this.Resources = resources;
            this.Notresources = notresources;
            this.Actions = actions;
            this.Notactions = notactions;
            this.Effect = effect;
        }
        
        /// <summary>
        /// Gets or Sets Resources
        /// </summary>
        [DataMember(Name="resources", EmitDefaultValue=false)]
        public Resources Resources { get; set; }

        /// <summary>
        /// Targeted resource will be those resources NOT in this list. The \&quot;resources&#x60;\&quot; field must be empty to use this field.
        /// </summary>
        /// <value>Targeted resource will be those resources NOT in this list. The \&quot;resources&#x60;\&quot; field must be empty to use this field.</value>
        [DataMember(Name="notresources", EmitDefaultValue=false)]
        public Resources Notresources { get; set; }

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [DataMember(Name="actions", EmitDefaultValue=false)]
        public Actions Actions { get; set; }

        /// <summary>
        /// Targeted actions will be those actions NOT in this list. The \&quot;actions\&quot; field must be empty to use this field.
        /// </summary>
        /// <value>Targeted actions will be those actions NOT in this list. The \&quot;actions\&quot; field must be empty to use this field.</value>
        [DataMember(Name="notactions", EmitDefaultValue=false)]
        public Actions Notactions { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Statement {\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  Notresources: ").Append(Notresources).Append("\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("  Notactions: ").Append(Notactions).Append("\n");
            sb.Append("  Effect: ").Append(Effect).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Statement);
        }

        /// <summary>
        /// Returns true if Statement instances are equal
        /// </summary>
        /// <param name="input">Instance of Statement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Statement input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Resources == input.Resources ||
                    (this.Resources != null &&
                    this.Resources.Equals(input.Resources))
                ) && 
                (
                    this.Notresources == input.Notresources ||
                    (this.Notresources != null &&
                    this.Notresources.Equals(input.Notresources))
                ) && 
                (
                    this.Actions == input.Actions ||
                    (this.Actions != null &&
                    this.Actions.Equals(input.Actions))
                ) && 
                (
                    this.Notactions == input.Notactions ||
                    (this.Notactions != null &&
                    this.Notactions.Equals(input.Notactions))
                ) && 
                (
                    this.Effect == input.Effect ||
                    (this.Effect != null &&
                    this.Effect.Equals(input.Effect))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Resources != null)
                    hashCode = hashCode * 59 + this.Resources.GetHashCode();
                if (this.Notresources != null)
                    hashCode = hashCode * 59 + this.Notresources.GetHashCode();
                if (this.Actions != null)
                    hashCode = hashCode * 59 + this.Actions.GetHashCode();
                if (this.Notactions != null)
                    hashCode = hashCode * 59 + this.Notactions.GetHashCode();
                if (this.Effect != null)
                    hashCode = hashCode * 59 + this.Effect.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
