/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing Clause
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClauseTests
    {
        // TODO uncomment below to declare an instance variable for Clause
        //private Clause instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Clause
            //instance = new Clause();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Clause
        /// </summary>
        [Test]
        public void ClauseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Clause
            //Assert.IsInstanceOfType<Clause> (instance, "variable 'instance' is a Clause");
        }


        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Test]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }
        /// <summary>
        /// Test the property 'Op'
        /// </summary>
        [Test]
        public void OpTest()
        {
            // TODO unit test for the property 'Op'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Negate'
        /// </summary>
        [Test]
        public void NegateTest()
        {
            // TODO unit test for the property 'Negate'
        }

    }

}
