/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing EnvironmentBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvironmentBodyTests
    {
        // TODO uncomment below to declare an instance variable for EnvironmentBody
        //private EnvironmentBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvironmentBody
            //instance = new EnvironmentBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvironmentBody
        /// </summary>
        [Test]
        public void EnvironmentBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvironmentBody
            //Assert.IsInstanceOfType<EnvironmentBody> (instance, "variable 'instance' is a EnvironmentBody");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'DefaultTtl'
        /// </summary>
        [Test]
        public void DefaultTtlTest()
        {
            // TODO unit test for the property 'DefaultTtl'
        }

    }

}
