/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing Environment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvironmentTests
    {
        // TODO uncomment below to declare an instance variable for Environment
        //private Environment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Environment
            //instance = new Environment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Environment
        /// </summary>
        [Test]
        public void EnvironmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Environment
            //Assert.IsInstanceOfType<Environment> (instance, "variable 'instance' is a Environment");
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'MobileKey'
        /// </summary>
        [Test]
        public void MobileKeyTest()
        {
            // TODO unit test for the property 'MobileKey'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'DefaultTtl'
        /// </summary>
        [Test]
        public void DefaultTtlTest()
        {
            // TODO unit test for the property 'DefaultTtl'
        }
        /// <summary>
        /// Test the property 'SecureMode'
        /// </summary>
        [Test]
        public void SecureModeTest()
        {
            // TODO unit test for the property 'SecureMode'
        }
        /// <summary>
        /// Test the property 'DefaultTrackEvents'
        /// </summary>
        [Test]
        public void DefaultTrackEventsTest()
        {
            // TODO unit test for the property 'DefaultTrackEvents'
        }

    }

}
