/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing FeatureFlagConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureFlagConfigTests
    {
        // TODO uncomment below to declare an instance variable for FeatureFlagConfig
        //private FeatureFlagConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureFlagConfig
            //instance = new FeatureFlagConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureFlagConfig
        /// </summary>
        [Test]
        public void FeatureFlagConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeatureFlagConfig
            //Assert.IsInstanceOfType<FeatureFlagConfig> (instance, "variable 'instance' is a FeatureFlagConfig");
        }


        /// <summary>
        /// Test the property 'On'
        /// </summary>
        [Test]
        public void OnTest()
        {
            // TODO unit test for the property 'On'
        }
        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Test]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }
        /// <summary>
        /// Test the property 'Salt'
        /// </summary>
        [Test]
        public void SaltTest()
        {
            // TODO unit test for the property 'Salt'
        }
        /// <summary>
        /// Test the property 'Sel'
        /// </summary>
        [Test]
        public void SelTest()
        {
            // TODO unit test for the property 'Sel'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Test]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Test]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
        /// <summary>
        /// Test the property 'Fallthrough'
        /// </summary>
        [Test]
        public void FallthroughTest()
        {
            // TODO unit test for the property 'Fallthrough'
        }
        /// <summary>
        /// Test the property 'OffVariation'
        /// </summary>
        [Test]
        public void OffVariationTest()
        {
            // TODO unit test for the property 'OffVariation'
        }
        /// <summary>
        /// Test the property 'Prerequisites'
        /// </summary>
        [Test]
        public void PrerequisitesTest()
        {
            // TODO unit test for the property 'Prerequisites'
        }
        /// <summary>
        /// Test the property 'TrackEvents'
        /// </summary>
        [Test]
        public void TrackEventsTest()
        {
            // TODO unit test for the property 'TrackEvents'
        }

    }

}
