/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing FeatureFlag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureFlagTests
    {
        // TODO uncomment below to declare an instance variable for FeatureFlag
        //private FeatureFlag instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureFlag
            //instance = new FeatureFlag();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureFlag
        /// </summary>
        [Test]
        public void FeatureFlagInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeatureFlag
            //Assert.IsInstanceOfType<FeatureFlag> (instance, "variable 'instance' is a FeatureFlag");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'IncludeInSnippet'
        /// </summary>
        [Test]
        public void IncludeInSnippetTest()
        {
            // TODO unit test for the property 'IncludeInSnippet'
        }
        /// <summary>
        /// Test the property 'Temporary'
        /// </summary>
        [Test]
        public void TemporaryTest()
        {
            // TODO unit test for the property 'Temporary'
        }
        /// <summary>
        /// Test the property 'MaintainerId'
        /// </summary>
        [Test]
        public void MaintainerIdTest()
        {
            // TODO unit test for the property 'MaintainerId'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Variations'
        /// </summary>
        [Test]
        public void VariationsTest()
        {
            // TODO unit test for the property 'Variations'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Maintainer'
        /// </summary>
        [Test]
        public void MaintainerTest()
        {
            // TODO unit test for the property 'Maintainer'
        }
        /// <summary>
        /// Test the property 'Environments'
        /// </summary>
        [Test]
        public void EnvironmentsTest()
        {
            // TODO unit test for the property 'Environments'
        }

    }

}
