/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing Member
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MemberTests
    {
        // TODO uncomment below to declare an instance variable for Member
        //private Member instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Member
            //instance = new Member();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Member
        /// </summary>
        [Test]
        public void MemberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Member
            //Assert.IsInstanceOfType<Member> (instance, "variable 'instance' is a Member");
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PendingInvite'
        /// </summary>
        [Test]
        public void PendingInviteTest()
        {
            // TODO unit test for the property 'PendingInvite'
        }
        /// <summary>
        /// Test the property 'IsBeta'
        /// </summary>
        [Test]
        public void IsBetaTest()
        {
            // TODO unit test for the property 'IsBeta'
        }
        /// <summary>
        /// Test the property 'CustomRoles'
        /// </summary>
        [Test]
        public void CustomRolesTest()
        {
            // TODO unit test for the property 'CustomRoles'
        }

    }

}
