/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing Rule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleTests
    {
        // TODO uncomment below to declare an instance variable for Rule
        //private Rule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rule
            //instance = new Rule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rule
        /// </summary>
        [Test]
        public void RuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Rule
            //Assert.IsInstanceOfType<Rule> (instance, "variable 'instance' is a Rule");
        }


        /// <summary>
        /// Test the property 'Variation'
        /// </summary>
        [Test]
        public void VariationTest()
        {
            // TODO unit test for the property 'Variation'
        }
        /// <summary>
        /// Test the property 'Rollout'
        /// </summary>
        [Test]
        public void RolloutTest()
        {
            // TODO unit test for the property 'Rollout'
        }
        /// <summary>
        /// Test the property 'Clauses'
        /// </summary>
        [Test]
        public void ClausesTest()
        {
            // TODO unit test for the property 'Clauses'
        }

    }

}
