/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing Statement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatementTests
    {
        // TODO uncomment below to declare an instance variable for Statement
        //private Statement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Statement
            //instance = new Statement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Statement
        /// </summary>
        [Test]
        public void StatementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Statement
            //Assert.IsInstanceOfType<Statement> (instance, "variable 'instance' is a Statement");
        }


        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Notresources'
        /// </summary>
        [Test]
        public void NotresourcesTest()
        {
            // TODO unit test for the property 'Notresources'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Notactions'
        /// </summary>
        [Test]
        public void NotactionsTest()
        {
            // TODO unit test for the property 'Notactions'
        }
        /// <summary>
        /// Test the property 'Effect'
        /// </summary>
        [Test]
        public void EffectTest()
        {
            // TODO unit test for the property 'Effect'
        }

    }

}
