/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing UserSegmentRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSegmentRuleTests
    {
        // TODO uncomment below to declare an instance variable for UserSegmentRule
        //private UserSegmentRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSegmentRule
            //instance = new UserSegmentRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSegmentRule
        /// </summary>
        [Test]
        public void UserSegmentRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSegmentRule
            //Assert.IsInstanceOfType<UserSegmentRule> (instance, "variable 'instance' is a UserSegmentRule");
        }


        /// <summary>
        /// Test the property 'Clauses'
        /// </summary>
        [Test]
        public void ClausesTest()
        {
            // TODO unit test for the property 'Clauses'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'BucketBy'
        /// </summary>
        [Test]
        public void BucketByTest()
        {
            // TODO unit test for the property 'BucketBy'
        }

    }

}
