/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;
using LaunchDarklyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing UserSettingsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSettingsBodyTests
    {
        // TODO uncomment below to declare an instance variable for UserSettingsBody
        //private UserSettingsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSettingsBody
            //instance = new UserSettingsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSettingsBody
        /// </summary>
        [Test]
        public void UserSettingsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSettingsBody
            //Assert.IsInstanceOfType<UserSettingsBody> (instance, "variable 'instance' is a UserSettingsBody");
        }


        /// <summary>
        /// Test the property 'Setting'
        /// </summary>
        [Test]
        public void SettingTest()
        {
            // TODO unit test for the property 'Setting'
        }

    }

}
