/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LaunchDarklyAPI.Client;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing CustomRolesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CustomRolesApiTests
    {
        private CustomRolesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CustomRolesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomRolesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CustomRolesApi
            //Assert.IsInstanceOfType(typeof(CustomRolesApi), instance, "instance is a CustomRolesApi");
        }

        
        /// <summary>
        /// Test DeleteCustomRole
        /// </summary>
        [Test]
        public void DeleteCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customRoleKey = null;
            //instance.DeleteCustomRole(customRoleKey);
            
        }
        
        /// <summary>
        /// Test GetCustomRole
        /// </summary>
        [Test]
        public void GetCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customRoleKey = null;
            //var response = instance.GetCustomRole(customRoleKey);
            //Assert.IsInstanceOf<CustomRole> (response, "response is CustomRole");
        }
        
        /// <summary>
        /// Test GetCustomRoles
        /// </summary>
        [Test]
        public void GetCustomRolesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetCustomRoles();
            //Assert.IsInstanceOf<CustomRoles> (response, "response is CustomRoles");
        }
        
        /// <summary>
        /// Test PatchCustomRole
        /// </summary>
        [Test]
        public void PatchCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customRoleKey = null;
            //List<PatchOperation> patchDelta = null;
            //var response = instance.PatchCustomRole(customRoleKey, patchDelta);
            //Assert.IsInstanceOf<CustomRole> (response, "response is CustomRole");
        }
        
        /// <summary>
        /// Test PostCustomRole
        /// </summary>
        [Test]
        public void PostCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomRoleBody customRoleBody = null;
            //instance.PostCustomRole(customRoleBody);
            
        }
        
    }

}
