/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LaunchDarklyAPI.Client;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing EnvironmentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvironmentsApiTests
    {
        private EnvironmentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvironmentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvironmentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvironmentsApi
            //Assert.IsInstanceOfType(typeof(EnvironmentsApi), instance, "instance is a EnvironmentsApi");
        }

        
        /// <summary>
        /// Test DeleteEnvironment
        /// </summary>
        [Test]
        public void DeleteEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //instance.DeleteEnvironment(projectKey, environmentKey);
            
        }
        
        /// <summary>
        /// Test GetEnvironment
        /// </summary>
        [Test]
        public void GetEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //var response = instance.GetEnvironment(projectKey, environmentKey);
            //Assert.IsInstanceOf<Environment> (response, "response is Environment");
        }
        
        /// <summary>
        /// Test PatchEnvironment
        /// </summary>
        [Test]
        public void PatchEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //List<PatchOperation> patchDelta = null;
            //var response = instance.PatchEnvironment(projectKey, environmentKey, patchDelta);
            //Assert.IsInstanceOf<Environment> (response, "response is Environment");
        }
        
        /// <summary>
        /// Test PostEnvironment
        /// </summary>
        [Test]
        public void PostEnvironmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //EnvironmentBody environmentBody = null;
            //instance.PostEnvironment(projectKey, environmentBody);
            
        }
        
    }

}
