/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LaunchDarklyAPI.Client;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UsersApiTests
    {
        private UsersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UsersApi
            //Assert.IsInstanceOfType(typeof(UsersApi), instance, "instance is a UsersApi");
        }

        
        /// <summary>
        /// Test DeleteUser
        /// </summary>
        [Test]
        public void DeleteUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //string userKey = null;
            //instance.DeleteUser(projectKey, environmentKey, userKey);
            
        }
        
        /// <summary>
        /// Test GetSearchUsers
        /// </summary>
        [Test]
        public void GetSearchUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //string q = null;
            //int? limit = null;
            //int? offset = null;
            //decimal? after = null;
            //var response = instance.GetSearchUsers(projectKey, environmentKey, q, limit, offset, after);
            //Assert.IsInstanceOf<Users> (response, "response is Users");
        }
        
        /// <summary>
        /// Test GetUser
        /// </summary>
        [Test]
        public void GetUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //string userKey = null;
            //var response = instance.GetUser(projectKey, environmentKey, userKey);
            //Assert.IsInstanceOf<User> (response, "response is User");
        }
        
        /// <summary>
        /// Test GetUsers
        /// </summary>
        [Test]
        public void GetUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectKey = null;
            //string environmentKey = null;
            //int? limit = null;
            //string h = null;
            //string scrollId = null;
            //var response = instance.GetUsers(projectKey, environmentKey, limit, h, scrollId);
            //Assert.IsInstanceOf<Users> (response, "response is Users");
        }
        
    }

}
