/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LaunchDarklyAPI.Client;
using LaunchDarklyAPI.Api;
using LaunchDarklyAPI.Model;

namespace LaunchDarklyAPI.Test
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WebhooksApiTests
    {
        private WebhooksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WebhooksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhooksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WebhooksApi
            //Assert.IsInstanceOfType(typeof(WebhooksApi), instance, "instance is a WebhooksApi");
        }

        
        /// <summary>
        /// Test DeleteWebhook
        /// </summary>
        [Test]
        public void DeleteWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resourceId = null;
            //instance.DeleteWebhook(resourceId);
            
        }
        
        /// <summary>
        /// Test GetWebhook
        /// </summary>
        [Test]
        public void GetWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resourceId = null;
            //var response = instance.GetWebhook(resourceId);
            //Assert.IsInstanceOf<Webhook> (response, "response is Webhook");
        }
        
        /// <summary>
        /// Test GetWebhooks
        /// </summary>
        [Test]
        public void GetWebhooksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWebhooks();
            //Assert.IsInstanceOf<Webhooks> (response, "response is Webhooks");
        }
        
        /// <summary>
        /// Test PatchWebhook
        /// </summary>
        [Test]
        public void PatchWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string resourceId = null;
            //List<PatchOperation> patchDelta = null;
            //var response = instance.PatchWebhook(resourceId, patchDelta);
            //Assert.IsInstanceOf<Webhook> (response, "response is Webhook");
        }
        
        /// <summary>
        /// Test PostWebhook
        /// </summary>
        [Test]
        public void PostWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebhookBody webhookBody = null;
            //instance.PostWebhook(webhookBody);
            
        }
        
    }

}
