/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using LaunchDarklyAPI.Client;
using LaunchDarklyAPI.Model;

namespace LaunchDarklyAPI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICustomRolesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns></returns>
        void DeleteCustomRole (string customRoleKey);

        /// <summary>
        /// Delete a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteCustomRoleWithHttpInfo (string customRoleKey);
        /// <summary>
        /// Get one custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>CustomRole</returns>
        CustomRole GetCustomRole (string customRoleKey);

        /// <summary>
        /// Get one custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>ApiResponse of CustomRole</returns>
        ApiResponse<CustomRole> GetCustomRoleWithHttpInfo (string customRoleKey);
        /// <summary>
        /// Return a complete list of custom roles.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CustomRoles</returns>
        CustomRoles GetCustomRoles ();

        /// <summary>
        /// Return a complete list of custom roles.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CustomRoles</returns>
        ApiResponse<CustomRoles> GetCustomRolesWithHttpInfo ();
        /// <summary>
        /// Modify a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>CustomRole</returns>
        CustomRole PatchCustomRole (string customRoleKey, List<PatchOperation> patchDelta);

        /// <summary>
        /// Modify a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>ApiResponse of CustomRole</returns>
        ApiResponse<CustomRole> PatchCustomRoleWithHttpInfo (string customRoleKey, List<PatchOperation> patchDelta);
        /// <summary>
        /// Create a new custom role.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns></returns>
        void PostCustomRole (CustomRoleBody customRoleBody);

        /// <summary>
        /// Create a new custom role.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostCustomRoleWithHttpInfo (CustomRoleBody customRoleBody);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteCustomRoleAsync (string customRoleKey);

        /// <summary>
        /// Delete a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteCustomRoleAsyncWithHttpInfo (string customRoleKey);
        /// <summary>
        /// Get one custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of CustomRole</returns>
        System.Threading.Tasks.Task<CustomRole> GetCustomRoleAsync (string customRoleKey);

        /// <summary>
        /// Get one custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of ApiResponse (CustomRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<CustomRole>> GetCustomRoleAsyncWithHttpInfo (string customRoleKey);
        /// <summary>
        /// Return a complete list of custom roles.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of CustomRoles</returns>
        System.Threading.Tasks.Task<CustomRoles> GetCustomRolesAsync ();

        /// <summary>
        /// Return a complete list of custom roles.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (CustomRoles)</returns>
        System.Threading.Tasks.Task<ApiResponse<CustomRoles>> GetCustomRolesAsyncWithHttpInfo ();
        /// <summary>
        /// Modify a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>Task of CustomRole</returns>
        System.Threading.Tasks.Task<CustomRole> PatchCustomRoleAsync (string customRoleKey, List<PatchOperation> patchDelta);

        /// <summary>
        /// Modify a custom role by key.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>Task of ApiResponse (CustomRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<CustomRole>> PatchCustomRoleAsyncWithHttpInfo (string customRoleKey, List<PatchOperation> patchDelta);
        /// <summary>
        /// Create a new custom role.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostCustomRoleAsync (CustomRoleBody customRoleBody);

        /// <summary>
        /// Create a new custom role.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostCustomRoleAsyncWithHttpInfo (CustomRoleBody customRoleBody);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CustomRolesApi : ICustomRolesApi
    {
        private LaunchDarklyAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomRolesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CustomRolesApi(String basePath)
        {
            this.Configuration = new LaunchDarklyAPI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = LaunchDarklyAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomRolesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CustomRolesApi(LaunchDarklyAPI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = LaunchDarklyAPI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = LaunchDarklyAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public LaunchDarklyAPI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public LaunchDarklyAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns></returns>
        public void DeleteCustomRole (string customRoleKey)
        {
             DeleteCustomRoleWithHttpInfo(customRoleKey);
        }

        /// <summary>
        /// Delete a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteCustomRoleWithHttpInfo (string customRoleKey)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->DeleteCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteCustomRoleAsync (string customRoleKey)
        {
             await DeleteCustomRoleAsyncWithHttpInfo(customRoleKey);

        }

        /// <summary>
        /// Delete a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteCustomRoleAsyncWithHttpInfo (string customRoleKey)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->DeleteCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get one custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>CustomRole</returns>
        public CustomRole GetCustomRole (string customRoleKey)
        {
             ApiResponse<CustomRole> localVarResponse = GetCustomRoleWithHttpInfo(customRoleKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get one custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>ApiResponse of CustomRole</returns>
        public ApiResponse< CustomRole > GetCustomRoleWithHttpInfo (string customRoleKey)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->GetCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRole>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRole) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRole)));
        }

        /// <summary>
        /// Get one custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of CustomRole</returns>
        public async System.Threading.Tasks.Task<CustomRole> GetCustomRoleAsync (string customRoleKey)
        {
             ApiResponse<CustomRole> localVarResponse = await GetCustomRoleAsyncWithHttpInfo(customRoleKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get one custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <returns>Task of ApiResponse (CustomRole)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CustomRole>> GetCustomRoleAsyncWithHttpInfo (string customRoleKey)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->GetCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRole>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRole) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRole)));
        }

        /// <summary>
        /// Return a complete list of custom roles. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CustomRoles</returns>
        public CustomRoles GetCustomRoles ()
        {
             ApiResponse<CustomRoles> localVarResponse = GetCustomRolesWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return a complete list of custom roles. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CustomRoles</returns>
        public ApiResponse< CustomRoles > GetCustomRolesWithHttpInfo ()
        {

            var localVarPath = "/roles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomRoles", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRoles>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRoles) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRoles)));
        }

        /// <summary>
        /// Return a complete list of custom roles. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of CustomRoles</returns>
        public async System.Threading.Tasks.Task<CustomRoles> GetCustomRolesAsync ()
        {
             ApiResponse<CustomRoles> localVarResponse = await GetCustomRolesAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return a complete list of custom roles. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (CustomRoles)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CustomRoles>> GetCustomRolesAsyncWithHttpInfo ()
        {

            var localVarPath = "/roles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomRoles", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRoles>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRoles) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRoles)));
        }

        /// <summary>
        /// Modify a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>CustomRole</returns>
        public CustomRole PatchCustomRole (string customRoleKey, List<PatchOperation> patchDelta)
        {
             ApiResponse<CustomRole> localVarResponse = PatchCustomRoleWithHttpInfo(customRoleKey, patchDelta);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Modify a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>ApiResponse of CustomRole</returns>
        public ApiResponse< CustomRole > PatchCustomRoleWithHttpInfo (string customRoleKey, List<PatchOperation> patchDelta)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->PatchCustomRole");
            // verify the required parameter 'patchDelta' is set
            if (patchDelta == null)
                throw new ApiException(400, "Missing required parameter 'patchDelta' when calling CustomRolesApi->PatchCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter
            if (patchDelta != null && patchDelta.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(patchDelta); // http body (model) parameter
            }
            else
            {
                localVarPostBody = patchDelta; // byte array
            }

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRole>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRole) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRole)));
        }

        /// <summary>
        /// Modify a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>Task of CustomRole</returns>
        public async System.Threading.Tasks.Task<CustomRole> PatchCustomRoleAsync (string customRoleKey, List<PatchOperation> patchDelta)
        {
             ApiResponse<CustomRole> localVarResponse = await PatchCustomRoleAsyncWithHttpInfo(customRoleKey, patchDelta);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Modify a custom role by key. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleKey">The custom role key.</param>
        /// <param name="patchDelta">Requires a JSON Patch representation of the desired changes to the project. &#39;http://jsonpatch.com/&#39;</param>
        /// <returns>Task of ApiResponse (CustomRole)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CustomRole>> PatchCustomRoleAsyncWithHttpInfo (string customRoleKey, List<PatchOperation> patchDelta)
        {
            // verify the required parameter 'customRoleKey' is set
            if (customRoleKey == null)
                throw new ApiException(400, "Missing required parameter 'customRoleKey' when calling CustomRolesApi->PatchCustomRole");
            // verify the required parameter 'patchDelta' is set
            if (patchDelta == null)
                throw new ApiException(400, "Missing required parameter 'patchDelta' when calling CustomRolesApi->PatchCustomRole");

            var localVarPath = "/roles/{customRoleKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleKey != null) localVarPathParams.Add("customRoleKey", this.Configuration.ApiClient.ParameterToString(customRoleKey)); // path parameter
            if (patchDelta != null && patchDelta.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(patchDelta); // http body (model) parameter
            }
            else
            {
                localVarPostBody = patchDelta; // byte array
            }

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CustomRole>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CustomRole) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CustomRole)));
        }

        /// <summary>
        /// Create a new custom role. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns></returns>
        public void PostCustomRole (CustomRoleBody customRoleBody)
        {
             PostCustomRoleWithHttpInfo(customRoleBody);
        }

        /// <summary>
        /// Create a new custom role. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> PostCustomRoleWithHttpInfo (CustomRoleBody customRoleBody)
        {
            // verify the required parameter 'customRoleBody' is set
            if (customRoleBody == null)
                throw new ApiException(400, "Missing required parameter 'customRoleBody' when calling CustomRolesApi->PostCustomRole");

            var localVarPath = "/roles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleBody != null && customRoleBody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(customRoleBody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = customRoleBody; // byte array
            }

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create a new custom role. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostCustomRoleAsync (CustomRoleBody customRoleBody)
        {
             await PostCustomRoleAsyncWithHttpInfo(customRoleBody);

        }

        /// <summary>
        /// Create a new custom role. 
        /// </summary>
        /// <exception cref="LaunchDarklyAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customRoleBody">New role or roles to create.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PostCustomRoleAsyncWithHttpInfo (CustomRoleBody customRoleBody)
        {
            // verify the required parameter 'customRoleBody' is set
            if (customRoleBody == null)
                throw new ApiException(400, "Missing required parameter 'customRoleBody' when calling CustomRolesApi->PostCustomRole");

            var localVarPath = "/roles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (customRoleBody != null && customRoleBody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(customRoleBody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = customRoleBody; // byte array
            }

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostCustomRole", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
